version: '3.4'

services:
  rafsandb:
    image: mcr.microsoft.com/mssql/server:2017-latest 
  rafsanwebapp-client:
    image: rafsanulhasan/rafsanulhasanapp/clientwebapp:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password="Dragon404"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/DevSkill.Web.pfx
      - ASPNETCORE_URLS=http://+:54381;https://+:44311;http://0.0.0.0:54381;https://0.0.0.0:44311;http://120.50.14.60:8000;https://120.50.14.60:9000;http://120.50.14.61:8000;https://120.50.14.61:9000
      - ASPNETCORE_HTTPS_PORT=44331
      - ASPNETCORE_ConnectionStrings__DefaultConnection=${DefaultConnection:-Server=120.50.14.60;Database=DevSkillV2;User Id=sa;Password=Dragon404; Persist Security Info=true; MultipleActiveResultSet=true}
      #- NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages;/root/.nuget/fallbackpackages2
      - NODE_ENV=Development
    build:
      context: .
      dockerfile: Applications/Web/SPA/Client/Dockerfile.debug
    extra_hosts:
      - "devskillwebserver:10.0.75.1"
    ports:
      - "54381:54381"
      - "44331:44311"
      - "10.0.75.1:54381:54381"
      - "10.0.75.1:44331:44311"
    volumes:
      - ${APPDATA}/Roaming/Microsoft/UserSecrets/:/root/.microsoft/usersecrets:ro
      #- ${APPDATA}/Roaming/ASP.NET/Https:/root/.aspnet/https/:ro
      - ${APPDATA}/Local/mkcert:/root/.local/share/mkcert/:rw
      #- ${USERPROFILE}\.nuget\packages:/root/.nuget/packages:ro
      #- ${ProgramFiles}\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages2:ro

  rafsanwebapp-server:
    image: rafsanulhasan/rafsanulhasanapp/serverwebappandapi:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password="Dragon404"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/DevSkill.Services.Membership.pfx
      - ASPNETCORE_URLS=http://+:54382;https://+:44312;http://0.0.0.0:54382;https://0.0.0.0:44312;http://120.50.14.60:8001;https://120.50.14.60:9001;http://120.50.14.61:8001;https://120.50.14.61:9001
      - ASPNETCORE_HTTPS_PORT=44332
      - ASPNETCORE_ConnectionStrings__DefaultConnection=${DefaultConnection:-Server=120.50.14.60;Database=DevSkillV2;User Id=sa;Password=Dragon404; Persist Security Info=true; MultipleActiveResultSet=true}
      #- NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages;/root/.nuget/fallbackpackages2
      - NODE_ENV=Development
    build:
      context: .
      dockerfile: Applications/Web/SPA/Client/Dockerfile.debug
    extra_hosts:
      - "devskillauthserver:10.0.75.1"
    ports:
      - "54381:54381"
      - "44332:44312"
      - "10.0.75.1:54382:54382"
      - "10.0.75.1:44332:44312"
    volumes:
      - ${APPDATA}/Roaming/Microsoft/UserSecrets/:/root/.microsoft/usersecrets:ro
      #- ${APPDATA}/Roaming/ASP.NET/Https:/root/.aspnet/https/:ro
      - ${APPDATA}/Local/mkcert:/root/.local/share/mkcert/:rw
      #- ${USERPROFILE}\.nuget\packages:/root/.nuget/packages:ro
      #- ${ProgramFiles}\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages2:ro